name: foodhub
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl_phone_number_input: ^0.7.3+1
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  firebase_analytics: ^10.5.1
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  cloud_firestore: ^4.9.3
  google_sign_in: ^6.1.5
  mailer: ^6.0.1
  image_picker: ^1.0.4
  firebase_storage: ^11.4.0
  cached_network_image: ^3.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/

  fonts:
  - family: SofiaPro
    fonts:
      - asset: fonts/sofia-pro-cufonfonts/Sofia Pro Regular Az.otf
      - asset: fonts/sofia-pro-cufonfonts/Sofia Pro Bold Az.otf
      