name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.0' # specify the Flutter version

    - name: Get dependencies
      run: flutter pub get

    - name: Analyze
      run: flutter analyze

    - name: Test
      run: flutter test

